In [1]:
import pandas as pd

data = {
    'Name': ['Asha', 'Ravi', 'Priya', 'Rahul', 'Sneha'],
    'Age': [20, 21, 20, 22, 21],
    'Marks': [85, 70, 95, 60, 80],
    'Hours_Studied': [3, 2, 5, 1, 4]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4

In [2]:
import pandas as pd

data = {
    'Name': ['Asha', 'Ravi', 'Priya', 'Rahul', 'Sneha'],
    'Age': [20, 21, 20, 22, 21],
    'Marks': [85, 70, 95, 60, 80],
    'Hours_Studied': [3, 2, 5, 1, 4]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4

In [3]:
print(df.head())
print(df.shape)
print(df.info())
print(df.describe())

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4
(5, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      str
 1   Age            5 non-null      int64
 2   Marks          5 non-null      int64
 3   Hours_Studied  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 212.0 bytes
None
            Age      Marks  Hours_Studied
count   5.00000   5.000000       5.000000
mean   20.80000  78.000000       3.000000
std     0.83666  13.509256       1.581139
min    20.00000  60.000000       1.000000
25%    20.00000  70.000000       2.000000
50%    21.00000  80.000000       3.000000
75%    21.00000  85.000000       4.000000
max    22.00000  95.000000       5.000000

In [4]:
print(df.head())
print(df.shape)
print(df.info())
print(df.describe())

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4
(5, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      str
 1   Age            5 non-null      int64
 2   Marks          5 non-null      int64
 3   Hours_Studied  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 212.0 bytes
None
            Age      Marks  Hours_Studied
count   5.00000   5.000000       5.000000
mean   20.80000  78.000000       3.000000
std     0.83666  13.509256       1.581139
min    20.00000  60.000000       1.000000
25%    20.00000  70.000000       2.000000
50%    21.00000  80.000000       3.000000
75%    21.00000  85.000000       4.000000
max    22.00000  95.000000       5.000000

In [5]:
print(df.head())
print(df.shape)
print(df.info())
print(df.describe())

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4
(5, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      str
 1   Age            5 non-null      int64
 2   Marks          5 non-null      int64
 3   Hours_Studied  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 212.0 bytes
None
            Age      Marks  Hours_Studied
count   5.00000   5.000000       5.000000
mean   20.80000  78.000000       3.000000
std     0.83666  13.509256       1.581139
min    20.00000  60.000000       1.000000
25%    20.00000  70.000000       2.000000
50%    21.00000  80.000000       3.000000
75%    21.00000  85.000000       4.000000
max    22.00000  95.000000       5.000000

In [6]:
print(df.head())
print(df.shape)
print(df.info())
print(df.describe())

    Name  Age  Marks  Hours_Studied
0   Asha   20     85              3
1   Ravi   21     70              2
2  Priya   20     95              5
3  Rahul   22     60              1
4  Sneha   21     80              4
(5, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      str
 1   Age            5 non-null      int64
 2   Marks          5 non-null      int64
 3   Hours_Studied  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 212.0 bytes
None
            Age      Marks  Hours_Studied
count   5.00000   5.000000       5.000000
mean   20.80000  78.000000       3.000000
std     0.83666  13.509256       1.581139
min    20.00000  60.000000       1.000000
25%    20.00000  70.000000       2.000000
50%    21.00000  80.000000       3.000000
75%    21.00000  85.000000       4.000000
max    22.00000  95.000000       5.000000

In [ ]:
Exploratory Data Analysis helps us understand the structure of a dataset, calculate summary statistics, identify patterns, visualize relationships, and detect missing or duplicate data. In this sample, study hours and marks show a positive relationship.